<?php

namespace ApiBundle\Repository;

/**
 * DebtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebtRepository extends \Doctrine\ORM\EntityRepository
{
}
