<?php

namespace ApiBundle\Repository;

/**
 * DebtorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebtorRepository extends \Doctrine\ORM\EntityRepository
{
}
