<?php

namespace ApiBundle\Repository;
use ApiBundle\Entity\Entity;

/**
 * EntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllButAdmin()
    {
        $qb = $this->createQueryBuilder('e');

        $qb
            ->select('e')
            ->where($qb->expr()->in(
                'e.type',
                array(
                    'Watcher',
                    'Notifier'
                )
            ))
        ;

        $returnArr = array();
        $results = $qb->getQuery()->getResult();

        if (!empty($results)) {
            /** @var Entity $entity */
            foreach ($results as $entity) {
                $returnArr[] = array(
                    'id' => $entity->getId(),
                    'name' => $entity->getName(),
                    'email' => $entity->getEmail(),
                    'identifier' => $entity->getIdentifier(),
                    'role' => $entity->getType(),
                    'createdAt' => $entity->getCreatedAt()->getTimestamp(),
                );
            }
        }

        return $returnArr;
    }
}
