<?php

namespace ApiBundle\Repository;

/**
 * PayoutNoticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayoutNoticeRepository extends \Doctrine\ORM\EntityRepository
{
}
